# -*- coding: utf-8 -*-
"""GNNs_Credit_Card_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcp_kPPPEPMVmNETRTj0TfpHdAXbgxz7

Akhilesh:
"""

# ============================================================
# Member C — FAST, FIXED PIPELINE (NumPy 2.0 safe, Py3.12-safe FAISS)
# ============================================================

# ---- Installs (quiet) ----
!pip -q install -U kagglehub xgboost
# faiss-gpu wheels are not published for py3.12; install faiss-cpu (fast C++ backend).
!pip -q install -U faiss-cpu
# PyG for torch 2.4.0 on Colab CUDA 12.1
!pip -q install torch-geometric==2.5.3 torch-scatter==2.1.2 -f https://data.pyg.org/whl/torch-2.4.0+cu121.html

# ---- Imports ----
import os, random, warnings, time, hashlib
import numpy as np, pandas as pd
warnings.filterwarnings("ignore")

from pathlib import Path
import kagglehub

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.calibration import CalibratedClassifierCV
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import NearestNeighbors, LocalOutlierFactor
from sklearn.ensemble import IsolationForest
from sklearn.decomposition import PCA

import xgboost as xgb

import torch, torch.nn as nn, torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv

# ---------------- Speed presets & timers ----------------
def tic(msg=""):
    global _t0; _t0=time.time()
    if msg: print(f"[⏱] {msg} ...", flush=True)
def toc(msg="done"):
    print(f"[⏱] {msg} in {time.time()-_t0:.2f}s", flush=True)

try: torch.set_float32_matmul_precision("high")
except Exception: pass

# ---------------- Config (fast-by-default) ----------------
SEED = 42
FAST = True

NEG_CAP_TRAIN = 80_000      # cap #negatives in TRAIN only (speed)
BATCH_TRIP    = 1024         # triplet batch (O(B^2) cost)
TRIP_EPOCHS   = 10
GNN_EPOCHS    = 20
GNN_TRIALS    = 6

K_GRAPH       = 8            # k for mutual/temporal graphs
GRAPH_CHOICES = ["temporal_knn", "mutual_knn"]
EMB_LIST      = [24, 32]
HID_LIST      = [64, 96]
DROPOUT_LIST  = [0.0, 0.2]
FOCAL_G_LIST  = [1.5, 2.0]
LR_LIST       = [1e-3, 2e-3]
DT_MAX        = 36_000       # (~10h lookback for temporal edges)
TOP_PCTS      = [0.5, 1.0, 2.0]

# ---------------- Repro & device ----------------
def seed_all(s=SEED):
    random.seed(s); np.random.seed(s)
    torch.manual_seed(s); torch.cuda.manual_seed_all(s)
    torch.backends.cudnn.deterministic=True; torch.backends.cudnn.benchmark=False
seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
AMP = torch.cuda.is_available()
print(f"Device: {device} | AMP: {AMP} | FAST: {FAST}")

# ---------------- Helpers ----------------
def norm01(a):
    a = np.asarray(a, dtype=np.float64)
    return (a - np.min(a)) / (np.ptp(a) + 1e-12)

def recall_at_top_pct(y_true, scores, pct):
    n = max(1, int(np.ceil(len(y_true)*pct/100.0)))
    idx = np.argsort(-scores)[:n]
    return y_true[idx].sum() / max(1, y_true.sum())

def eval_scores(name, y_true, p):
    ap  = average_precision_score(y_true, p)
    roc = roc_auc_score(y_true, p)
    row = {"model":name, "AP":ap, "ROC":roc}
    for k in TOP_PCTS: row[f"R@{k}%"]=recall_at_top_pct(y_true,p,k)
    return row

def calibrate_prefit(model, Xv, yv):
    try:
        cal = CalibratedClassifierCV(model, method='isotonic', cv='prefit'); cal.fit(Xv, yv)
    except Exception:
        cal = CalibratedClassifierCV(model, method='sigmoid',  cv='prefit'); cal.fit(Xv, yv)
    return cal

# ---------------- Load dataset ----------------
CSV_PATH=None
try:
    root = kagglehub.dataset_download("mlg-ulb/creditcardfraud")
    cand = Path(root)/"creditcard.csv"
    if cand.exists(): CSV_PATH=str(cand)
except Exception: pass
if CSV_PATH is None:
    for p in ["/kaggle/input/creditcardfraud/creditcard.csv","/content/creditcard.csv","creditcard.csv"]:
        if os.path.exists(p): CSV_PATH=p; break
if CSV_PATH is None:
    raise FileNotFoundError("creditcard.csv not found. Upload it to the runtime and rerun.")

df = pd.read_csv(CSV_PATH).sort_values("Time").reset_index(drop=True)

# Chronological 80/10/10 split
t = df["Time"].values
q80,q90 = np.quantile(t,[0.80,0.90])
train_df = df[t<=q80]
val_df   = df[(t>q80)&(t<=q90)]
test_df  = df[t>q90]

# Cap negatives in TRAIN only (speed)
if NEG_CAP_TRAIN:
    pos = train_df[train_df.Class==1]
    neg = train_df[train_df.Class==0]
    if len(neg)>NEG_CAP_TRAIN:
        neg = neg.sample(NEG_CAP_TRAIN, random_state=SEED)
    train_df = pd.concat([pos,neg]).sort_values("Time")

feat_cols = [f"V{i}" for i in range(1,29)] + ["Amount"]
def prep(df_part, scaler=None):
    X = df_part[feat_cols].copy()
    X["Amount"] = np.log1p(X["Amount"])
    scaler = StandardScaler().fit(X) if scaler is None else scaler
    return scaler.transform(X), df_part["Class"].astype(int).values, scaler

X_train,y_train,scaler = prep(train_df,None)
X_val  ,y_val  ,_      = prep(val_df,scaler)
X_test ,y_test ,_      = prep(test_df,scaler)
T_train = train_df["Time"].values.astype(np.int64)
T_val   = val_df["Time"].values.astype(np.int64)
T_test  = test_df["Time"].values.astype(np.int64)

print(f"Splits — Train:{len(y_train)} (+{y_train.sum()}) | Val:{len(y_val)} (+{y_val.sum()}) | Test:{len(y_test)} (+{y_test.sum()})")

# =========================================================
# A) MLP (small random search) + calibration
# =========================================================
def tune_mlp(Xtr,ytr,Xv,yv,trials=6):
    rng = np.random.default_rng(SEED)
    best=(None,-1)
    for i in range(trials):
        hl1 = int(rng.choice([128,192])); hl2=int(rng.choice([64,96]))
        alpha=float(rng.choice([1e-4,5e-5,1e-5])); lr=float(rng.choice([1e-3,5e-4]))
        clf = MLPClassifier(hidden_layer_sizes=(hl1,hl2), alpha=alpha,
                            learning_rate_init=lr, max_iter=35, random_state=SEED,
                            early_stopping=True)
        clf.fit(Xtr,ytr)
        cal = calibrate_prefit(clf, Xv, yv)
        p = cal.predict_proba(Xv)[:,1]
        ap = average_precision_score(yv,p)
        print(f"[MLP] trial{i} AP(val)={ap:.4f}  cfg=({hl1},{hl2}) alpha={alpha} lr={lr}")
        if ap>best[1]: best=(cal,ap)
    return best[0]

tic("MLP tuning")
mlp_cal = tune_mlp(X_train,y_train,X_val,y_val,trials=6)
p_test_mlp = mlp_cal.predict_proba(X_test)[:,1]
res_mlp = eval_scores("MLP (tuned, cal)", y_test, p_test_mlp)
toc("MLP done")
print(res_mlp)

# =========================================================
# B) Triplet embedding (balanced batches) + SAFE FAISS kNN + GraphSAGE
# =========================================================
class Encoder(nn.Module):
    def __init__(self,in_dim,emb):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(in_dim,128), nn.ReLU(),
                                 nn.Linear(128,64),  nn.ReLU(),
                                 nn.Linear(64,emb))
        self.ln  = nn.LayerNorm(emb)
    def forward(self,x): return self.ln(self.net(x))

def pairwise_dist(x):
    xn=(x**2).sum(1,keepdim=True); return xn + xn.T - 2*(x@x.T)

def batch_hard_triplet_loss(emb,y,margin=0.2):
    B,dev=emb.size(0),emb.device
    with torch.no_grad():
        D_=pairwise_dist(emb)
        same=y[:,None].eq(y[None,:]); diag=torch.eye(B,dtype=torch.bool,device=dev)
        Dp=D_.clone(); Dp[~same|diag]=-1e9; pos=Dp.argmax(1)
        Dn=D_.clone(); Dn[same]=1e9;  neg=Dn.argmin(1)
    D=pairwise_dist(emb); ar=torch.arange(B,device=dev)
    hp,hn=D[ar,pos], D[ar,neg]
    return F.relu(margin + hp - hn).mean()

def make_balanced_batches(X,y,batch,steps):
    pos=np.where(y==1)[0]; neg=np.where(y==0)[0]
    rng=np.random.default_rng(SEED)
    for _ in range(steps):
        pi=rng.choice(pos,size=max(1,batch//2),replace=True)
        ni=rng.choice(neg,size=batch-len(pi),replace=False)
        idx=np.concatenate([pi,ni]); rng.shuffle(idx)
        yield idx

@torch.no_grad()
def embed(encoder, X):
    encoder.eval()
    xb=torch.tensor(X,dtype=torch.float32,device=device)
    out=[]
    for i in range(0,len(xb),8192):
        out.append(encoder(xb[i:i+8192]).detach().cpu())
    return torch.cat(out,0).numpy()

# ===== Safe FAISS kNN (GPU -> CPU -> sklearn fallback) =====
import numpy as np, torch
try:
    import faiss  # CPU or GPU module
    _FAISS_AVAILABLE = True
    def _faiss_has_gpu():
        try:
            return (torch.cuda.is_available() and
                    hasattr(faiss, "StandardGpuResources") and
                    hasattr(faiss, "index_cpu_to_all_gpus") and
                    hasattr(faiss, "get_num_gpus") and
                    faiss.get_num_gpus() > 0)
        except Exception:
            return False
    _FAISS_HAS_GPU = _faiss_has_gpu()
except Exception:
    faiss = None
    _FAISS_AVAILABLE = False
    _FAISS_HAS_GPU = False

def _knn_sklearn(query, ref, k):
    from sklearn.neighbors import NearestNeighbors
    k = min(k, len(ref))
    nn = NearestNeighbors(n_neighbors=k, n_jobs=-1).fit(ref)
    D, I = nn.kneighbors(query, n_neighbors=k, return_distance=True)
    return D, I

def _faiss_knn(query, ref=None, k=10, metric="L2", use_gpu=True):
    q = np.ascontiguousarray(query.astype("float32"))
    r = q if ref is None else np.ascontiguousarray(ref.astype("float32"))
    k = min(k, len(r))
    if not _FAISS_AVAILABLE:
        return _knn_sklearn(q, r, k)
    index = faiss.IndexFlatL2(r.shape[1]) if metric == "L2" else faiss.IndexFlatIP(r.shape[1])
    if use_gpu and _FAISS_HAS_GPU:
        index = faiss.index_cpu_to_all_gpus(index)
    index.add(r)
    D, I = index.search(q, k)
    return D, I

def build_mutual_knn(Z, k=K_GRAPH):
    _, idx = _faiss_knn(Z, None, k=k, metric="L2", use_gpu=True)
    N,K = idx.shape
    src = np.repeat(np.arange(N,dtype=np.int64),K)
    dst = idx.ravel().astype(np.int64)
    pairs   = np.ascontiguousarray(np.stack([src,dst],1))
    pairs_r = np.ascontiguousarray(pairs[:,::-1])
    st=np.dtype([('i',np.int64),('j',np.int64)])
    inter = np.intersect1d(pairs.view(st).reshape(-1), pairs_r.view(st).reshape(-1))
    mut = inter.view(np.int64).reshape(-1,2)
    s = np.concatenate([mut[:,0], mut[:,1]])
    d = np.concatenate([mut[:,1], mut[:,0]])
    return s,d

def build_temporal_knn_to_train(Zq, Ztr, Tq, Ttr, k=K_GRAPH, dt_max=DT_MAX, oversample=8):
    Kc = min(max(k*oversample, k), len(Ztr))
    _, idx = _faiss_knn(Zq, Ztr, k=Kc, metric="L2", use_gpu=True)
    srcL, dstL = [], []
    for i, cand in enumerate(idx):
        mask = (Ttr[cand] <= Tq[i])
        if dt_max is not None:
            mask = mask & ((Tq[i] - Ttr[cand]) <= dt_max)
        sel = cand[mask][:k]
        if sel.size==0: continue
        srcL.append(np.full(sel.size, i, dtype=np.int64)); dstL.append(sel.astype(np.int64))
    if not srcL: return np.array([],dtype=np.int64), np.array([],dtype=np.int64)
    return np.concatenate(srcL), np.concatenate(dstL)

# edge cache
_edge_cache={}
def _zhash(Z):
    m=hashlib.sha1(); m.update(Z.shape.__repr__().encode()); m.update(np.float32(Z[:min(len(Z),256)]).tobytes()); return m.hexdigest()
def cached_mutual_knn(Z,k):
    key=("mutual",k,_zhash(Z));
    if key in _edge_cache: return _edge_cache[key]
    e=build_mutual_knn(Z,k); _edge_cache[key]=e; return e
def cached_temporal_to_train(Zq,Ztr,Tq,Ttr,k,dt):
    key=("temporal",k,dt,_zhash(Zq),_zhash(Ztr))
    if key in _edge_cache: return _edge_cache[key]
    e=build_temporal_knn_to_train(Zq,Ztr,Tq,Ttr,k,dt); _edge_cache[key]=e; return e

# GraphSAGE
class SAGE(nn.Module):
    def __init__(self,in_dim,h=64,drop=0.2):
        super().__init__()
        self.s1=SAGEConv(in_dim,h); self.s2=SAGEConv(h,h)
        self.drop=nn.Dropout(drop); self.lin=nn.Linear(h,1)
    def forward(self,x,ei):
        x=F.relu(self.s1(x,ei)); x=self.drop(x)
        x=F.relu(self.s2(x,ei)); x=self.drop(x)
        return self.lin(x).squeeze(-1)

def focal_bce(logits, targets, pos_weight, gamma=2.0):
    bce = F.binary_cross_entropy_with_logits(logits, targets, reduction='none', pos_weight=pos_weight)
    p = torch.sigmoid(logits); pt = torch.where(targets==1, p, 1-p)
    return ((1-pt)**gamma * bce).mean()

def train_gnn_conf(Xtr,ytr,Xv,yv,Ttr,Tv, graph_mode, emb_dim, h, drop, gamma, lr, k=K_GRAPH):
    # Triplet encoder
    enc=Encoder(Xtr.shape[1],emb_dim).to(device)
    opt=torch.optim.Adam(enc.parameters(),lr=1e-3,weight_decay=1e-4)
    scaler=torch.cuda.amp.GradScaler(enabled=AMP)
    steps=int(np.ceil(len(ytr)/BATCH_TRIP))
    best, bad, pat = 1e9, 0, 4
    tic("Triplet")
    for ep in range(TRIP_EPOCHS):
        enc.train(); losses=[]
        for idx in make_balanced_batches(Xtr,ytr,BATCH_TRIP,steps):
            xb=torch.tensor(Xtr[idx],dtype=torch.float32,device=device)
            yb=torch.tensor(ytr[idx],dtype=torch.long,device=device)
            opt.zero_grad(set_to_none=True)
            with torch.cuda.amp.autocast(enabled=AMP):
                z=enc(xb); loss=batch_hard_triplet_loss(z,yb,margin=0.2)
            scaler.scale(loss).backward(); scaler.step(opt); scaler.update()
            losses.append(loss.item())
        ml=float(np.mean(losses))
        if ml<best-1e-4: best,bad=ml,0
        else:
            bad+=1
            if bad>=pat: break
    toc("Triplet done")

    tic("Embeddings")
    Ztr = embed(enc, Xtr); Zv = embed(enc, Xv)
    toc("Embeddings done")

    tic("Graphs")
    s_tr,d_tr = cached_mutual_knn(Ztr,k)
    if graph_mode=="temporal_knn":
        s_v,d_v = cached_temporal_to_train(Zv,Ztr,Tv,Ttr,k,DT_MAX)
    else:
        nnm=NearestNeighbors(n_neighbors=min(k,len(Ztr))).fit(Ztr)
        _, idxv = nnm.kneighbors(Zv)
        s_v=np.repeat(np.arange(len(Zv)), idxv.shape[1]); d_v=idxv.ravel().astype(np.int64)
    toc("Graphs built")

    x_tr=torch.tensor(Ztr,dtype=torch.float32,device=device)
    y_tr_t=torch.tensor(ytr,dtype=torch.long,device=device)
    ei_tr=torch.tensor([s_tr,d_tr],dtype=torch.long,device=device)

    x_all=torch.tensor(np.vstack([Ztr,Zv]),dtype=torch.float32,device=device)
    y_all=torch.tensor(np.concatenate([ytr,yv]),dtype=torch.long,device=device)
    ei_val=torch.cat([ei_tr, torch.tensor([s_v+len(Ztr), d_v],dtype=torch.long,device=device)], dim=1)
    val_mask=torch.zeros(x_all.size(0),dtype=torch.bool,device=device); val_mask[len(Ztr):]=True

    model=SAGE(in_dim=x_tr.size(1),h=h,drop=drop).to(device)
    pos_w=torch.tensor((len(ytr)-ytr.sum())/(ytr.sum()+1e-9),device=device).float()
    optm=torch.optim.Adam(model.parameters(),lr=lr,weight_decay=1e-4)
    scaler=torch.cuda.amp.GradScaler(enabled=AMP)

    best_ap=-1; bad=0; pat=5
    tic("SAGE")
    for ep in range(GNN_EPOCHS):
        model.train(); optm.zero_grad(set_to_none=True)
        with torch.cuda.amp.autocast(enabled=AMP):
            logits=model(x_tr, ei_tr)
            loss=focal_bce(logits, y_tr_t.float(), pos_w, gamma=gamma)
        scaler.scale(loss).backward(); scaler.step(optm); scaler.update()
        model.eval()
        with torch.no_grad(), torch.cuda.amp.autocast(enabled=AMP):
            pv=torch.sigmoid(model(x_all, ei_val))[val_mask].float().cpu().numpy()
        ap=average_precision_score(yv,pv)
        print(f"[SAGE] ep{ep:02d} loss={loss.item():.4f} AP(val)={ap:.4f}")
        if ap>best_ap+1e-4:
            best_ap, best_state, bad = ap, {k:v.detach().cpu() for k,v in model.state_dict().items()}, 0
        else:
            bad+=1
            if bad>=pat: break
    toc("SAGE done")
    model.load_state_dict(best_state)
    return enc, model, best_ap

# Small random search on val
rng=np.random.default_rng(SEED)
best = (-1,None,None,None)
for i in range(GNN_TRIALS):
    conf=dict(
        graph_mode=str(rng.choice(GRAPH_CHOICES)),
        emb_dim=int(rng.choice(EMB_LIST)),
        h=int(rng.choice(HID_LIST)),
        drop=float(rng.choice(DROPOUT_LIST)),
        gamma=float(rng.choice(FOCAL_G_LIST)),
        lr=float(rng.choice(LR_LIST)),
        k=K_GRAPH
    )
    print(f"\n[GNN trial {i}] {conf}")
    enc, model, apv = train_gnn_conf(X_train,y_train,X_val,y_val,T_train,T_val, **conf)
    if apv>best[0]: best=(apv, conf, enc, model)
best_ap, best_conf, best_enc, best_model = best
print("\nBest GNN on val:", best_conf, "AP(val)=", round(best_ap,4))

# Re-embed full sets & build val/test packs with best config
Ztr = embed(best_enc, X_train); Zv = embed(best_enc, X_val); Zt = embed(best_enc, X_test)
s_tr,d_tr = cached_mutual_knn(Ztr, best_conf["k"])
if best_conf["graph_mode"]=="temporal_knn":
    s_v,d_v = cached_temporal_to_train(Zv,Ztr,T_val,T_train,best_conf["k"],DT_MAX)
    s_t,d_t = cached_temporal_to_train(Zt,Ztr,T_test,T_train,best_conf["k"],DT_MAX)
else:
    nnv=NearestNeighbors(n_neighbors=min(best_conf["k"],len(Ztr))).fit(Ztr)
    _, idxv = nnv.kneighbors(Zv); _, idxt = nnv.kneighbors(Zt)
    s_v=np.repeat(np.arange(len(Zv)), idxv.shape[1]); d_v=idxv.ravel().astype(np.int64)
    s_t=np.repeat(np.arange(len(Zt)), idxt.shape[1]); d_t=idxt.ravel().astype(np.int64)

x_val_all=torch.tensor(np.vstack([Ztr,Zv]),dtype=torch.float32,device=device)
y_val_all=torch.tensor(np.concatenate([y_train,y_val]),dtype=torch.long,device=device)
ei_val=torch.cat([torch.tensor([s_tr,d_tr],dtype=torch.long,device=device),
                  torch.tensor([s_v+len(Ztr), d_v],dtype=torch.long,device=device)], dim=1)
val_mask=torch.zeros(x_val_all.size(0),dtype=torch.bool,device=device); val_mask[len(Ztr):]=True
val_pack=(x_val_all,y_val_all,ei_val,val_mask)

x_tst_all=torch.tensor(np.vstack([Ztr,Zt]),dtype=torch.float32,device=device)
y_tst_all=torch.tensor(np.concatenate([y_train,y_test]),dtype=torch.long,device=device)
ei_tst=torch.cat([torch.tensor([s_tr,d_tr],dtype=torch.long,device=device),
                  torch.tensor([s_t+len(Ztr), d_t],dtype=torch.long,device=device)], dim=1)
test_mask=torch.zeros(x_tst_all.size(0),dtype=torch.bool,device=device); test_mask[len(Ztr):]=True
test_pack=(x_tst_all,y_tst_all,ei_tst,test_mask)

def gnn_predict(model, pack):
    x,_y,ei,mask = pack
    model.eval()
    with torch.no_grad():
        logits=model(x,ei)
        return torch.sigmoid(logits)[mask].float().cpu().numpy()

p_val_gnn  = gnn_predict(best_model, val_pack)
p_test_gnn = gnn_predict(best_model, test_pack)
res_gnn = eval_scores(f"GraphSAGE (tuned, {best_conf['graph_mode']}, k={best_conf['k']})", y_test, p_test_gnn)
print(res_gnn)

# =========================================================
# C) Anomaly models (tuned quick)
# =========================================================
def tune_if(Xtr,ytr,Xv,yv,trials=3):
    rng=np.random.default_rng(SEED); best=(-1,None)
    for _ in range(trials):
        n_est=int(rng.choice([200,300,400])); maxs=rng.choice([1.0,0.7])
        mss="auto" if maxs==1.0 else int(maxs*len(Xtr))
        clf=IsolationForest(n_estimators=n_est, max_samples=mss, random_state=SEED, n_jobs=-1)
        clf.fit(Xtr)
        ap=average_precision_score(yv, norm01(-clf.score_samples(Xv)))
        if ap>best[0]: best=(ap,clf)
    return best[1]

def tune_lof(Xtr,ytr,Xv,yv,trials=3):
    rng=np.random.default_rng(SEED); best=(-1,None)
    for _ in range(trials):
        k=int(rng.choice([20,30,40])); metric=str(rng.choice(["euclidean","manhattan"]))
        clf=LocalOutlierFactor(n_neighbors=k, novelty=True, metric=metric)
        clf.fit(Xtr)
        ap=average_precision_score(yv, norm01(-clf.decision_function(Xv)))
        if ap>best[0]: best=(ap,clf)
    return best[1]

class AE(nn.Module):
    def __init__(self,d, bottleneck=24):
        super().__init__()
        self.enc=nn.Sequential(nn.Linear(d,128), nn.ReLU(), nn.Dropout(0.1),
                               nn.Linear(128,64), nn.ReLU(),
                               nn.Linear(64,bottleneck))
        self.dec=nn.Sequential(nn.Linear(bottleneck,64), nn.ReLU(),
                               nn.Linear(64,128), nn.ReLU(),
                               nn.Linear(128,d))
    def forward(self,x): z=self.enc(x); return self.dec(z)

def train_ae(Xtr, epochs=6):
    ae=AE(Xtr.shape[1]).to(device)
    opt=torch.optim.Adam(ae.parameters(),lr=1e-3,weight_decay=1e-5); crit=nn.MSELoss()
    for ep in range(epochs):
        idx=np.random.permutation(len(Xtr))
        for i in range(0,len(idx),2048):
            xb=torch.tensor(Xtr[idx[i:i+2048]],dtype=torch.float32,device=device)
            opt.zero_grad(set_to_none=True); rec=ae(xb); loss=crit(rec,xb); loss.backward(); opt.step()
    @torch.no_grad()
    def score(X):
        s=[]
        for i in range(0,len(X),2048):
            xb=torch.tensor(X[i:i+2048],dtype=torch.float32,device=device)
            e=((ae(xb)-xb)**2).mean(1).detach().cpu().numpy(); s.append(e)
        return norm01(np.concatenate(s))
    return ae, score

tic("Anomaly models")
iso = tune_if(X_train,y_train,X_val,y_val); s_test_iso = norm01(-iso.score_samples(X_test))
lof = tune_lof(X_train,y_train,X_val,y_val); s_test_lof = norm01(-lof.decision_function(X_test))
ae, ae_score = train_ae(X_train); s_test_ae = ae_score(X_test)
res_if  = eval_scores("IsolationForest (tuned)", y_test, s_test_iso)
res_lof = eval_scores("LOF (tuned)",            y_test, s_test_lof)
res_ae  = eval_scores("AE anomaly (tuned)",     y_test, s_test_ae)
toc("Anomaly done")
print(res_if); print(res_lof); print(res_ae)

# =========================================================
# D) Neighbor-risk prior (from train embeddings) + Meta blender (XGB)
# =========================================================
def neighbor_risk_prior(Ztr,ytr,Zq,k=30,sigma=None):
    D,I = _faiss_knn(Zq, Ztr, k=min(k,len(Ztr)), metric="L2", use_gpu=True)
    if sigma is None:
        s = D[D>0]; sigma = (np.median(s) if s.size else 1.0) + 1e-6
    w = np.exp(-D / sigma)
    num=(w * ytr[I]).sum(1); den=w.sum(1) + 1e-12
    return (num/den).astype(np.float64)

risk_val  = neighbor_risk_prior(Ztr, y_train, Zv, k=30)
risk_test = neighbor_risk_prior(Ztr, y_train, Zt, k=30)

# Calibrate base scores for meta
from sklearn.isotonic import IsotonicRegression
cal_mlp = IsotonicRegression(out_of_bounds='clip').fit(mlp_cal.predict_proba(X_val)[:,1], y_val)
p_val_mlp  = cal_mlp.transform(mlp_cal.predict_proba(X_val)[:,1])
p_test_mlp = cal_mlp.transform(p_test_mlp)

cal_gnn = IsotonicRegression(out_of_bounds='clip').fit(p_val_gnn, y_val)
p_val_gnn_cal  = cal_gnn.transform(p_val_gnn)
p_test_gnn_cal = cal_gnn.transform(p_test_gnn)

s_val_iso = norm01(-iso.score_samples(X_val))
s_val_lof = norm01(-lof.decision_function(X_val))
s_val_ae  = ae_score(X_val)

V_meta = np.vstack([
    p_val_mlp, p_val_gnn_cal, s_val_iso, s_val_lof, s_val_ae, risk_val,
    p_val_mlp*p_val_gnn_cal, np.maximum(p_val_mlp, p_val_gnn_cal)
]).T
T_meta = np.vstack([
    p_test_mlp, p_test_gnn_cal, s_test_iso, s_test_lof, s_test_ae, risk_test,
    p_test_mlp*p_test_gnn_cal, np.maximum(p_test_mlp, p_test_gnn_cal)
]).T

scale_pos = (len(y_val)-y_val.sum())/max(1,y_val.sum())
xgb_meta = xgb.XGBClassifier(
    n_estimators=400, max_depth=3, learning_rate=0.05,
    subsample=0.9, colsample_bytree=0.9, eval_metric='aucpr',
    scale_pos_weight=scale_pos, tree_method='hist'
)
tic("Meta training")
xgb_meta.fit(V_meta, y_val)
p_test_meta = xgb_meta.predict_proba(T_meta)[:,1]
toc("Meta done")

res_meta = eval_scores("Stacked (XGB meta + risk)", y_test, p_test_meta)
print(res_meta)

# =========================================================
# E) Results + recall-at-budget counts
# =========================================================
def counts_at_pct(y_true, p, pct):
    n = max(1, int(np.ceil(len(y_true)*pct/100.0))); idx = np.argsort(-p)[:n]
    return n, int(y_true[idx].sum()), int(y_true.sum())

results=[res_meta, res_gnn, res_mlp, res_if, res_lof, res_ae]
bench=pd.DataFrame(results).sort_values("AP",ascending=False).reset_index(drop=True)
print("\n=== RESULTS (Member C, fast & fixed) ===")
print(bench.to_string(index=False))

print("\n--- Recall at review budgets ---")
for name, pred in [("Stacked", p_test_meta), (res_gnn["model"], p_test_gnn_cal), (res_mlp["model"], p_test_mlp)]:
    line=[name]
    for pct in TOP_PCTS:
        n,c,tot=counts_at_pct(y_test,pred,pct); line.append(f"{pct}%: {c}/{tot} in {n}")
        # you'll show how many frauds you'd catch if you reviewed only top k%
    print(" | ".join(line))

bench.to_csv("memberC_fast_results.csv", index=False)
print("\nSaved: memberC_fast_results.csv")

# =========================
# FAST CLUSTERING ADD-ON (Member C)
# =========================
# No extra installs. Uses sklearn only.
import numpy as np
from sklearn.cluster import MiniBatchKMeans
from sklearn.mixture import BayesianGaussianMixture
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score, roc_auc_score
import time, math, sys

def _tic(msg):
    _tic.t = time.time(); print(f"[⏱] {msg} ...", flush=True)
def _toc(msg="done"):
    print(f"[⏱] {msg} in {time.time()-_tic.t:.2f}s", flush=True)

rng = np.random.default_rng(SEED if 'SEED' in globals() else 42)

# ---------- choose space: use triplet embedding if available, else PCA(12) ----------
if 'Ztr' in globals() and isinstance(Ztr, np.ndarray):
    Xc_tr, Xc_va, Xc_te = Ztr, Zv, Zt
    space = "embedding"
else:
    _tic("PCA(12) for clustering space")
    _pca = PCA(n_components=12, random_state=SEED).fit(X_train)
    Xc_tr = _pca.transform(X_train)
    Xc_va = _pca.transform(X_val)
    Xc_te = _pca.transform(X_test)
    _toc("PCA ready"); space = "pca12"
print(f"[Clustering-fast] Space={space} | shapes: {Xc_tr.shape}, {Xc_va.shape}, {Xc_te.shape}")

# ---------- helpers ----------
def _z_from_train(train_vals, vals):
    sc = StandardScaler().fit(train_vals.reshape(-1,1))
    return sc.transform(vals.reshape(-1,1)).ravel()

def _rate_and_size(ids, y):
    ids = ids.astype(int)
    K = (ids.max()+1) if ids.size else 0
    size = np.bincount(ids.clip(min=0), minlength=K)
    fraud = np.bincount(ids.clip(min=0), minlength=K, weights=y)
    rate = np.divide(fraud, np.maximum(1, size), where=(size>0))
    return size, rate

# =========================================================
# 1) MiniBatchKMeans (super fast)
# =========================================================
_tic("MiniBatchKMeans")
n_km = 8
km = MiniBatchKMeans(
    n_clusters=n_km, random_state=SEED, batch_size=2048,
    n_init=3, max_iter=80, reassignment_ratio=0.01
)
km.fit(Xc_tr)
cid_tr = km.labels_
cid_va = km.predict(Xc_va)
cid_te = km.predict(Xc_te)

# dist to own centroid (z-scored using train)
dist_tr = np.linalg.norm(Xc_tr - km.cluster_centers_[cid_tr], axis=1)
dist_va = np.linalg.norm(Xc_va - km.cluster_centers_[cid_va], axis=1)
dist_te = np.linalg.norm(Xc_te - km.cluster_centers_[cid_te], axis=1)
dist_va_z = _z_from_train(dist_tr, dist_va)
dist_te_z = _z_from_train(dist_tr, dist_te)

# cluster priors from TRAIN (no leakage)
size_km, rate_km = _rate_and_size(cid_tr, y_train)
km_logsize_va = np.log1p(size_km[cid_va])
km_logsize_te = np.log1p(size_km[cid_te])
km_rate_va    = rate_km[cid_va]
km_rate_te    = rate_km[cid_te]

feat_km_val = np.column_stack([dist_va_z, km_logsize_va, km_rate_va])
feat_km_tst = np.column_stack([dist_te_z, km_logsize_te, km_rate_te])
_toc("MiniBatchKMeans done")

# =========================================================
# 2) Bayesian GMM (diag; fit on capped subset for speed)
# =========================================================
_tic("Bayesian GMM (diag, n=8; capped fit)")
cap = 40_000  # cap train rows used to fit GMM
sub_idx = np.arange(len(Xc_tr))
if len(sub_idx) > cap:
    sub_idx = rng.choice(sub_idx, size=cap, replace=False)
bgmm = BayesianGaussianMixture(
    n_components=8, covariance_type='diag', max_iter=150,
    random_state=SEED, weight_concentration_prior_type='dirichlet_distribution',
    reg_covar=1e-6
).fit(Xc_tr[sub_idx])

# score & soft posteriors
nll_tr = -bgmm.score_samples(Xc_tr)
nll_va = -bgmm.score_samples(Xc_va)
nll_te = -bgmm.score_samples(Xc_te)
nll_va_z = _z_from_train(nll_tr, nll_va)
nll_te_z = _z_from_train(nll_tr, nll_te)

pro_va = bgmm.predict_proba(Xc_va); pro_te = bgmm.predict_proba(Xc_te)
maxp_va = pro_va.max(1); maxp_te = pro_te.max(1)
# normalized entropy (0=confident, 1=uniform)
ent_va = -(pro_va*np.log(pro_va+1e-12)).sum(1) / math.log(pro_va.shape[1])
ent_te = -(pro_te*np.log(pro_te+1e-12)).sum(1) / math.log(pro_te.shape[1])

feat_gmm_val = np.column_stack([nll_va_z, maxp_va, ent_va])
feat_gmm_tst = np.column_stack([nll_te_z, maxp_te, ent_te])
_toc("BGMM done")

# ---------------------------------------------------------
# Combine clustering features & augment meta
# ---------------------------------------------------------
CLUST_FAST_NAMES = ["km_dist_z","km_logsize","km_rate","bgmm_nll_z","bgmm_maxp","bgmm_ent"]
V_cluster_fast = np.column_stack([feat_km_val, feat_gmm_val])
T_cluster_fast = np.column_stack([feat_km_tst, feat_gmm_tst])
print(f"[Clustering-fast] Features: {len(CLUST_FAST_NAMES)} → {CLUST_FAST_NAMES}")

# If your original meta features exist, extend them; else just use clustering features
try:
    V_meta_plus = np.hstack([V_meta, V_cluster_fast])
    T_meta_plus = np.hstack([T_meta, T_cluster_fast])
except NameError:
    V_meta_plus, T_meta_plus = V_cluster_fast, T_cluster_fast

# =========================================================
# Retrain a small XGB meta (fast)
# =========================================================
_tic("XGB meta (fast) retrain with clustering features")
scale_pos = (len(y_val)-y_val.sum())/max(1,y_val.sum())
xgb_meta_fast = xgb.XGBClassifier(
    n_estimators=250, max_depth=3, learning_rate=0.07,
    subsample=0.9, colsample_bytree=0.9, eval_metric='aucpr',
    scale_pos_weight=scale_pos, tree_method='hist', random_state=SEED
)
xgb_meta_fast.fit(V_meta_plus, y_val)
p_test_meta_fast = xgb_meta_fast.predict_proba(T_meta_plus)[:,1]
_toc("Meta done")

# -------- report & optionally replace originals --------
def _recall_at(p, y, pct):
    n = max(1, int(np.ceil(len(y)*pct/100.0)))
    idx = np.argsort(-p)[:n]
    return y[idx].sum()/max(1,y.sum())

ap_new  = average_precision_score(y_test, p_test_meta_fast)
roc_new = roc_auc_score(y_test, p_test_meta_fast)
ap_old  = average_precision_score(y_test, p_test_meta) if 'p_test_meta' in globals() else np.nan

print("\n=== FAST Meta + Clustering ===")
print(f"AP(new) = {ap_new:.6f}   ROC(new) = {roc_new:.6f}   AP(old) = {ap_old:.6f}")
for pct in [0.5, 1.0, 2.0]:
    print(f"Recall@{pct}% = {_recall_at(p_test_meta_fast, y_test, pct):.3f}")

# make downstream code use the faster/better meta
p_test_meta = p_test_meta_fast
xgb_meta    = xgb_meta_fast

# (Optional) persist the feature block
np.savez_compressed("memberC_fast_cluster_feats.npz",
    V_cluster=V_cluster_fast, T_cluster=T_cluster_fast,
    names=np.array(CLUST_FAST_NAMES, dtype=object))
print("Saved: memberC_fast_cluster_feats.npz")

# =========================
# Member C — RESULTS VIEWER (quick)
# =========================
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from sklearn.metrics import average_precision_score, roc_auc_score, precision_recall_curve, roc_curve, auc

def _recall_at(y, p, pct):
    n = max(1, int(np.ceil(len(y)*pct/100.0)))
    idx = np.argsort(-p)[:n]
    return y[idx].sum()/max(1, y.sum())

def _row(name, y, p):
    return dict(
        model=name,
        AP=average_precision_score(y, p),
        ROC=roc_auc_score(y, p),
        **{f"R@{k}%": _recall_at(y, p, k) for k in (0.5, 1.0, 2.0)}
    )

# --- collect whatever predictions exist ---
items = []
# New meta (fast + clustering). Try both names, fall back to p_test_meta.
if 'p_test_meta_fast' in globals():
    items.append(("Meta (fast+cluster)", y_test, p_test_meta_fast))
if 'p_test_meta' in globals():
    items.append(("Meta (current)", y_test, p_test_meta))

# Baselines
if 'p_test_gnn_cal' in globals(): items.append(("GNN (cal)", y_test, p_test_gnn_cal))
elif 'p_test_gnn' in globals():   items.append(("GNN", y_test, p_test_gnn))
if 'p_test_mlp' in globals():     items.append(("MLP (cal)", y_test, p_test_mlp))
if 's_test_iso' in globals():     items.append(("IsolationForest", y_test, s_test_iso))
if 's_test_lof' in globals():     items.append(("LOF", y_test, s_test_lof))
if 's_test_ae' in globals():      items.append(("AE", y_test, s_test_ae))

# --- table ---
rows = [_row(n, y, p) for n, y, p in items]
bench = pd.DataFrame(rows).sort_values("AP", ascending=False).reset_index(drop=True)
print("\n=== RESULTS (Member C) ===")
print(bench.to_string(index=False))

# Save for the report
bench.to_csv("memberC_results_view.csv", index=False)
print("\nSaved: memberC_results_view.csv")

# --- Show deltas if old meta is available (optional) ---
if ('p_test_meta_fast' in globals()) and ('p_test_meta' in globals()):
    ap_old = average_precision_score(y_test, p_test_meta)
    ap_new = average_precision_score(y_test, p_test_meta_fast)
    def R(pct, p): return _recall_at(y_test, p, pct)
    print("\nΔ vs current Meta:")
    print(f"  AP: {ap_new - ap_old:+.4f}   (new={ap_new:.4f}, old={ap_old:.4f})")
    for pct in (0.5, 1.0, 2.0):
        print(f"  Recall@{pct}%: {R(pct, p_test_meta_fast) - R(pct, p_test_meta):+.3f}")

# --- lightweight PR/ROC just for the main triage models (fast) ---
def _plot_pr(short):
    plt.figure()
    for n, y, p in short:
        pr, rc, _ = precision_recall_curve(y, p)
        ap = average_precision_score(y, p)
        plt.plot(rc, pr, label=f"{n} (AP={ap:.3f})")
    plt.xlabel("Recall"); plt.ylabel("Precision"); plt.title("Precision–Recall (Test)")
    plt.legend(); plt.grid(True); plt.show()

def _plot_roc(short):
    plt.figure()
    for n, y, p in short:
        fpr, tpr, _ = roc_curve(y, p); A = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f"{n} (ROC={A:.3f})")
    plt.plot([0,1],[0,1], linestyle="--")
    plt.xlabel("FPR"); plt.ylabel("TPR"); plt.title("ROC (Test)")
    plt.legend(); plt.grid(True); plt.show()

# choose the three most relevant series available
main = []
for label in ("Meta (fast+cluster)", "Meta (current)", "GNN (cal)", "GNN", "MLP (cal)"):
    for n, y, p in items:
        if n == label:
            main.append((n, y, p))
            break
if len(main) >= 2:
    _plot_pr(main[:3])
    _plot_roc(main[:3])

# --- Recall-at-budget summary sentence you can paste into slides ---
def _fmt_pct(x): return f"{100*x:.1f}%"
if 'p_test_meta_fast' in globals():
    r05 = _recall_at(y_test, p_test_meta_fast, 0.5)
    r10 = _recall_at(y_test, p_test_meta_fast, 1.0)
    r20 = _recall_at(y_test, p_test_meta_fast, 2.0)
    print("\nSlide-ready line:")
    print(f"Meta+Clustering retrieves {_fmt_pct(r05)} / {_fmt_pct(r10)} / {_fmt_pct(r20)} "
          "of frauds when reviewing top 0.5% / 1% / 2% of transactions.")

